name: Mirroring

on: [push, delete]

jobs:
  sync_to_openi:
    runs-on: ubuntu-latest
    steps:                                              # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@openi.pcl.ac.cn:mindspore-ecosystem/mindnlp.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.OPENI_SSH_PRIVATE_KEY }}