# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Pipe

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'mindnlp/**'
      - 'tests/ut/**'
      - '!mindnlp/dataset/**'
      - '!tests/ut/dataset/**'
      - '!docs/**'
      - '.github/workflows/ut_test.yaml'
  push:
    branches: [ "master" ]
    paths:
      - 'mindnlp/**'
      - '!mindnlp/dataset/**'
      - '!docs/**'

permissions:
  contents: read

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev_requirements.txt
    - name: Install MindSpore
      shell: bash
      env:
        OS: ubuntu-latest
        PYTHON: 3.7
        MS_USERNAME: ${{ secrets.MS_USERNAME }}
        MS_PASSWD: ${{ secrets.MS_PASSWD }}
      run: |
        python .github/gen_mindspore_url.py
        pip install -r download.txt
    - name: Analysing the mindnlp code with pylint
      run: |
        pylint mindnlp --rcfile=.github/pylint.conf
    - name: Analysing the tests code with pylint
      run: |
        pylint tests --rcfile=.github/pylint.conf

  ut-test:
    needs: pylint-check
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        python: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev_requirements.txt
    - name: Install MindSpore
      shell: bash
      env:
        OS: ${{ matrix.os }}
        PYTHON: ${{ matrix.python }}
        MS_USERNAME: ${{ secrets.MS_USERNAME }}
        MS_PASSWD: ${{ secrets.MS_PASSWD }}
      run: |
        python .github/gen_mindspore_url.py
        pip install -r download.txt
    - name: Test with pytest
      run: |
        pytest -m 'not dataset' tests/ut

  st-test:
    needs: ut-test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        python: [3.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev_requirements.txt
    - name: Install MindSpore
      shell: bash
      env:
        OS: ${{ matrix.os }}
        PYTHON: ${{ matrix.python }}
        MS_USERNAME: ${{ secrets.MS_USERNAME }}
        MS_PASSWD: ${{ secrets.MS_PASSWD }}
      run: |
        python .github/gen_mindspore_url.py
        pip install -r download.txt
    - name: Test ST with pytest
      run: |
        pytest tests/st
