# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Pipe

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'mindnlp/**'
      - 'tests/ut/**'
      - '!mindnlp/dataset/**'
      - '!tests/ut/dataset/**'
      - '!docs/**'
      - '.github/workflows/**'
  push:
    branches: [ "master" ]
    paths:
      - 'mindnlp/**'
      - '!mindnlp/dataset/**'
      - '!docs/**'

permissions:
  contents: read

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Install MindSpore
      shell: bash
      env:
        OS: ubuntu-latest
        PYTHON: 3.7
      run: |
        python .github/install_mindspore.py
        pip install -r download.txt
    - name: Analysing the mindnlp code with pylint
      run: |
        pylint mindnlp --rcfile=.github/pylint.conf
    - name: Analysing the tests code with pylint
      run: |
        pylint tests --rcfile=.github/pylint.conf

  ut-test:
    needs: pylint-check
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: avoid macos error
      if: matrix.os == 'macos-latest'
      run: rm -rf $RUNNER_TOOL_CACHE/Python/3.7.17
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Install MindSpore
      shell: bash
      env:
        OS: ${{ matrix.os }}
        PYTHON: ${{ matrix.python }}
      run: |
        python .github/install_mindspore.py
        pip install -r download.txt
    - name: Test with pytest on linux and macos
      if: matrix.os != 'windows-latest'
      run: |
        pytest -m 'not download and not gpu_only' tests/ut
    - name: Test with pytest on windows
      if: matrix.os == 'windows-latest'
      run: |
        pytest -m 'not download and not gpu_only' tests/ut --ignore=tests/ut/models

  release-test:
    needs: pylint-check
    strategy:
      matrix:
        ms_version: ['1.8.1', '1.9', '1.10']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Install MindSpore
      shell: bash
      run: |
        pip install mindspore==${{matrix.ms_version}}
    - name: Test with pytest
      run: |
        pytest -m 'not download and not gpu_only' --ignore=tests/ut/models tests/ut 

  st-test:
    needs: ut-test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Install MindSpore
      shell: bash
      env:
        OS: ${{ matrix.os }}
        PYTHON: ${{ matrix.python }}
      run: |
        python .github/install_mindspore.py
        pip install -r download.txt
    - name: Test ST with pytest
      run: |
        pytest tests/st

  kaggle-gpu-test:
    needs: pylint-check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository_owner == 'mindspore-lab'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - uses: "lvyufeng/action-kaggle-gpu-test@latest"
      with:
        kaggle_username: "${{ secrets.KAGGLE_USERNAME }}"
        kaggle_key: "${{ secrets.KAGGLE_API_KEY }}"
        kernel_name: mindnlp
        kernel_job_file: .github/kaggle_gpu_test.py
