name: Run dataset ut tests

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'mindnlp/dataset/**'
      - 'tests/ut/dataset/**'
      - '!docs/**'

permissions:
  contents: read

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Install MindSpore
      shell: bash
      env:
        OS: ubuntu-latest
        PYTHON: 3.7
      run: |
        python .github/install_mindspore.py
        pip install -r download.txt
    - name: Analysing the mindnlp code with pylint
      run: |
        pylint mindnlp --rcfile=.github/pylint.conf
    - name: Analysing the tests code with pylint
      run: |
        pylint tests/ut --rcfile=.github/pylint.conf

  dataset-ut-test:
    needs: pylint-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Install MindSpore
      shell: bash
      env:
        OS: ubuntu-latest
        PYTHON: 3.7
      run: |
        python .github/install_mindspore.py
        pip install -r download.txt
    - name: Test with pytest
      run: |
        pytest -m 'download and not local' --ignore=tests/ut/models tests/ut
